### ISSUE TITLE
A way to use _locale as prefix for both category and page

### ISSUE THREAD

**Issue by Gyvastis** [Orbitale/CmsBundle#11]
Is there a way to use `_locale` as a prefix both for category and page routes? 

My goal is to have SEO friendly routes for categories as I have for pages. Instead of `/c/news/` it would be better if I could have it same as pages without any additions just `/news`.

Any ideas how could I achieve this easily? If I leave `prefix:   /{_locale}/c/` for both of their routing settings, it doesn't pass through to the second one and throws a 404. Any way to go around this?

**Comment by Pierstoval** [comment]
It's really simple:

```yaml
# app/config/routing.yml
orbitale_cms_category:
    resource: "@OrbitaleCmsBundle/Resources/config/routing/categories.yaml"
    prefix:   /{_locale}/category/
    defaults: { _locale: '%locale%' }
    
orbitale_cms_page:
    resource: "@OrbitaleCmsBundle/Resources/config/routing/pages.yaml"
    prefix:   /{_locale}/page/
    defaults: { _locale: '%locale%' }
```

By adding defaults, you're sure to be able to generate routes even with no locale in the `generateUrl` method from the router, and as the routing context will automatically be updated with the specified locale in the URL, if a locale is present, all generated routes that need a locale will use the current request's one 😄

**Comment by Gyvastis** [comment]
Maybe I didn't make myself clear. I wanted to use something like this:
```
orbitale_cms_category:
    resource: "@OrbitaleCmsBundle/Resources/config/routing/categories.yaml"
    prefix:   /{_locale}/
    
orbitale_cms_page:
    resource: "@OrbitaleCmsBundle/Resources/config/routing/pages.yaml"
    prefix:   /{_locale}/
```
But obviously in this case the category controller needs to be modified not to throw 404 if the path does not exist and pass on to the page route. Though I ended up not using categories at all - I use parent pages and it solved my issue, so I just left category paths with different prefix.
